services:
  backend:
    build: ./backend
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - cavacamisa-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - cavacamisa-network
    environment:
      - VITE_API_URL=/api
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - cavacamisa-network
    restart: unless-stopped

networks:
  cavacamisa-network:
    driver: bridge
