services:
  backend:
    build: ./backend
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - cavacamisa-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - cavacamisa-network
    environment:
      - VITE_API_URL=/api
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - cavacamisa-network

networks:
  cavacamisa-network:
    driver: bridge

volumes:
  frontend_node_modules:
